### ISSUE TITLE
2015-04-11 やること @code0-sh

### ISSUE THREAD

**Issue by code0-sh** [OkinawaDevOps/okinawadevops.github.com#114]
React Nativeをさわってみる

- Getting Started
- Tutorial

他時間内で進めるところまで

**Comment by yamanetoshi** [comment]
@code0-sh 
すすめかたとか特に問題ないでしょうか?
なにかあれば mention 頂ければと存じます。

ちなみに今居るのは松江ですか?

**Comment by code0-sh** [comment]
今日は池袋にいます。
来月中頃までは東京にいますよ。
今日はよろしくお願いします。

**Comment by yamanetoshi** [comment]
6 月から、って話をどこかで見たので、今はどちらなのだろうかと思って次第ス。

こちらこそ今日はよろしくです。

**Comment by code0-sh** [comment]
merge 頂きましたのでこちらCloseします。
