### ISSUE TITLE
10 月開催

### ISSUE THREAD

**Issue by yamanetoshi** [OkinawaDevOps/okinawadevops.github.com#142]
したいなと思っています。いつが良いでしょ。

**Comment by yamanetoshi** [comment]
やまねですが、10.17 は無理らしいです。以降は調整可能ス。

**Comment by mura-** [comment]
遅くなりました。10.24あたりいかが？

**Comment by mura-** [comment]
このコミュには私とyamanesanしかいない説浮上
参加できそうな方誰か応答ﾓﾄﾑ！

**Comment by yamanetoshi** [comment]
ということでこの週末あたりにてリモートで云々しつつなはかそんになりそげな件

**Comment by yamanetoshi** [comment]
Beni cafe 4 名確保。

http://beniworking.com/
